<a href="https://colab.research.google.com/github/razieabbasi1999/Laptop-Price-Prediction-ML/blob/main/laptop-price-prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
from google.colab import drive

In [2]:
drive.mount('/content/drive')
os.environ['KAGGLE_API_TOKEN'] = "KGAT_f3f655892a6eae5067ca4c0263bd962a"

Mounted at /content/drive

In [3]:
folder_path = '/content/drive/MyDrive/Laptop_Project'

In [4]:
os.chdir(folder_path)

In [5]:
!pip install -q kaggle

In [6]:
!kaggle datasets download -d muhammetvarl/laptop-price

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/muhammetvarl/laptop-price
License(s): other
laptop-price.zip: Skipping, found more recently modified local copy (use --force to force download)

In [7]:
!unzip -o laptop-price.zip

Archive:  laptop-price.zip
  inflating: laptop_price.csv



---

# **Section Data Analysis**

In [8]:
import pandas as pd
df=pd.read_csv("laptop_price.csv", encoding="latin1")

In [9]:
df.head(50)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
5,6,Acer,Aspire 3,Notebook,15.6,1366x768,AMD A9-Series 9420 3GHz,4GB,500GB HDD,AMD Radeon R5,Windows 10,2.1kg,400.00
6,7,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,2139.97
7,8,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,256GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,1158.70
8,9,Asus,ZenBook UX430UN,Ultrabook,14.0,Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16GB,512GB SSD,Nvidia GeForce MX150,Windows 10,1.3kg,1495.00
9,10,Acer,Swift 3,Ultrabook,14.0,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Intel UHD Graphics 620,Windows 10,1.6kg,770.00
10,11,HP,250 G6,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,No OS,1.86kg,393.90
11,12,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,500GB HDD,Intel HD Graphics 520,No OS,1.86kg,344.99
12,13,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.8GHz,16GB,256GB SSD,AMD Radeon Pro 555,macOS,1.83kg,2439.97
13,14,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,256GB SSD,AMD Radeon R5 M430,Windows 10,2.2kg,498.90
14,15,Apple,"MacBook 12""",Ultrabook,12.0,IPS Panel Retina Display 2304x1440,Intel Core M m3 1.2GHz,8GB,256GB SSD,Intel HD Graphics 615,macOS,0.92kg,1262.40
15,16,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,256GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1518.55
16,17,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,256GB SSD,AMD Radeon R5 M430,Windows 10,2.2kg,745.00
17,18,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.9GHz,16GB,512GB SSD,AMD Radeon Pro 560,macOS,1.83kg,2858.00
18,19,Lenovo,IdeaPad 320-15IKB,Notebook,15.6,Full HD 1920x1080,Intel Core i3 7100U 2.4GHz,8GB,1TB HDD,Nvidia GeForce 940MX,No OS,2.2kg,499.00
19,20,Dell,XPS 13,Ultrabook,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,128GB SSD,Intel UHD Graphics 620,Windows 10,1.22kg,979.00
20,21,Asus,Vivobook E200HA,Netbook,11.6,1366x768,Intel Atom x5-Z8350 1.44GHz,2GB,32GB Flash Storage,Intel HD Graphics 400,Windows 10,0.98kg,191.90
21,22,Lenovo,Legion Y520-15IKBN,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,8GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1050,Windows 10,2.5kg,999.00
22,23,HP,255 G6,Notebook,15.6,1366x768,AMD E-Series E2-9000e 1.5GHz,4GB,500GB HDD,AMD Radeon R2,No OS,1.86kg,258.00
23,24,Dell,Inspiron 5379,2 in 1 Convertible,13.3,Full HD / Touchscreen 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Intel UHD Graphics 620,Windows 10,1.62kg,819.00
24,25,HP,15-BS101nv (i7-8550U/8GB/256GB/FHD/W10),Ultrabook,15.6,Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.91kg,659.00
25,26,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i3 6006U 2GHz,4GB,1TB HDD,Intel HD Graphics 520,Windows 10,2.3kg,418.64
26,27,Apple,MacBook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.6GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,Mac OS X,1.35kg,1099.00
27,28,Dell,Inspiron 5570,Notebook,15.6,Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,AMD Radeon 530,Windows 10,2.2kg,800.00
28,29,Dell,Latitude 5590,Ultrabook,15.6,Full HD 1920x1080,Intel Core i7 8650U 1.9GHz,8GB,256GB SSD + 256GB SSD,Intel UHD Graphics 620,Windows 10,1.88kg,1298.00
29,30,HP,ProBook 470,Notebook,17.3,Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,1TB HDD,Nvidia GeForce 930MX,Windows 10,2.5kg,896.00
30,31,Chuwi,"LapBook 15.6""",Notebook,15.6,Full HD 1920x1080,Intel Atom x5-Z8300 1.44GHz,4GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.89kg,244.99
31,32,Asus,E402WA-GA010T (E2-6110/2GB/32GB/W10),Notebook,14.0,1366x768,AMD E-Series E2-6110 1.5GHz,2GB,32GB Flash Storage,AMD Radeon R2,Windows 10,1.65kg,199.00
32,33,HP,17-ak001nv (A6-9220/4GB/500GB/Radeon,Notebook,17.3,Full HD 1920x1080,AMD A6-Series 9220 2.5GHz,4GB,500GB HDD,AMD Radeon 530,Windows 10,2.71kg,439.00
33,34,Dell,XPS 13,Ultrabook,13.3,Touchscreen / Quad HD+ 3200x1800,Intel Core i7 8550U 1.8GHz,16GB,512GB SSD,Intel UHD Graphics 620,Windows 10,1.2kg,1869.00
34,35,Apple,MacBook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.6GHz,8GB,256GB Flash Storage,Intel HD Graphics 6000,Mac OS X,1.35kg,998.00
35,36,Lenovo,IdeaPad 120S-14IAP,Notebook,14.0,1366x768,Intel Celeron Dual Core N3350 1.1GHz,4GB,64GB Flash Storage,Intel HD Graphics 500,Windows 10,1.44kg,249.00
36,37,Acer,Aspire 3,Notebook,15.6,1366x768,Intel Core i3 7130U 2.7GHz,4GB,1TB HDD,Intel HD Graphics 620,Linux,2.1kg,367.00
37,38,Dell,Inspiron 5770,Notebook,17.3,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,128GB SSD + 1TB HDD,AMD Radeon 530,Windows 10,2.8kg,979.00
38,39,HP,250 G6,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,4GB,1TB HDD,Intel HD Graphics 620,Windows 10,1.86kg,488.69
39,40,HP,ProBook 450,Notebook,15.6,Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Nvidia GeForce 930MX,Windows 10,2.1kg,879.00
40,41,Asus,X540UA-DM186 (i3-6006U/4GB/1TB/FHD/Linux),Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,1TB HDD,Intel HD Graphics 620,Linux,2kg,389.00
41,42,Dell,Inspiron 7577,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1060,Windows 10,2.65kg,1499.00
42,43,Asus,X542UQ-GO005 (i5-7200U/8GB/1TB/GeForce,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,8GB,1TB HDD,Nvidia GeForce 940MX,Linux,2.3kg,522.99
43,44,Acer,Aspire A515-51G,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,4GB,256GB SSD,Intel UHD Graphics 620,Windows 10,2.2kg,682.00
44,45,Dell,Inspiron 7773,2 in 1 Convertible,17.3,Full HD / Touchscreen 1920x1080,Intel Core i5 8250U 1.6GHz,12GB,1TB HDD,Nvidia GeForce 150MX,Windows 10,2.77kg,999.00
45,46,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.0GHz,8GB,256GB SSD,Intel Iris Graphics 540,macOS,1.37kg,1419.00
46,47,Lenovo,IdeaPad 320-15ISK,Notebook,15.6,1366x768,Intel Core i3 6006U 2GHz,4GB,128GB SSD,Intel HD Graphics 520,No OS,2.2kg,369.00
47,48,Asus,Rog Strix,Gaming,17.3,Full HD 1920x1080,AMD Ryzen 1700 3GHz,8GB,256GB SSD + 1TB HDD,AMD Radeon RX 580,Windows 10,3.2kg,1299.00
48,49,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,256GB SSD,AMD Radeon R5 M430,Windows 10,2.3kg,639.00
49,50,Asus,X751NV-TY001T (N4200/4GB/1TB/GeForce,Notebook,17.3,1366x768,Intel Pentium Quad Core N4200 1.1GHz,4GB,1TB HDD,Nvidia GeForce 920MX,Windows 10,2.8kg,466.00

In [10]:
df.shape

(1303, 13)

In [11]:
df.columns

Index(['laptop_ID', 'Company', 'Product', 'TypeName', 'Inches',
       'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight',
       'Price_euros'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Memory            1303 non-null   object
 9   Gpu               1303 non-null   object
 10  OpSys             1303 non-null   object
 11  Weight            1303 non-null   object
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 132.5+ KB

# **Preprocessing the " ScreenResolution " column :**

In [13]:
import numpy as np
import re

In [14]:
# ۱: IPS  ,  Touchscreen
df['IPS'] = df['ScreenResolution'].apply(lambda x: 1 if 'IPS' in x else 0)
df['Touchscreen'] = df['ScreenResolution'].apply(
lambda x: 1 if 'Touchscreen' in x else 0)

In [15]:
# 2.1: Height and width extraction function
def extract_resolution(res):
  match = re.search(r'(\d+)x(\d+)', res)
  if match:
    return int(match.group(1)), int(match.group(2))
  return None, None


# 2.2: Creating columns X_res and Y_res
res_tuples = df['ScreenResolution'].apply(extract_resolution)
df['X_res'], df['Y_res'] = zip(*res_tuples)

In [16]:
# 4: PPI calculation
df['PPI'] = (
(df['X_res'] ** 2 + df['Y_res'] ** 2) ** 0.5 / df['Inches']).round(2)

In [17]:
# ۵. نمایش هر ۵ ستون ساخته‌شده
df[['IPS', 'Touchscreen', 'X_res', 'Y_res', 'PPI']].head(30)

    IPS  Touchscreen  X_res  Y_res     PPI
0     1            0   2560   1600  226.98
1     0            0   1440    900  127.68
2     0            0   1920   1080  141.21
3     1            0   2880   1800  220.53
4     1            0   2560   1600  226.98
5     0            0   1366    768  100.45
6     1            0   2880   1800  220.53
7     0            0   1440    900  127.68
8     0            0   1920   1080  157.35
9     1            0   1920   1080  157.35
10    0            0   1366    768  100.45
11    0            0   1920   1080  141.21
12    1            0   2880   1800  220.53
13    0            0   1920   1080  141.21
14    1            0   2304   1440  226.42
15    1            0   2560   1600  226.98
16    0            0   1920   1080  141.21
17    1            0   2880   1800  220.53
18    0            0   1920   1080  141.21
19    1            1   1920   1080  165.63
20    0            0   1366    768  135.09
21    1            0   1920   1080  141.21
22    0            0   1366    768  100.45
23    0            1   1920   1080  165.63
24    0            0   1920   1080  141.21
25    0            0   1366    768  100.45
26    0            0   1440    900  127.68
27    0            0   1920   1080  141.21
28    0            0   1920   1080  141.21
29    0            0   1920   1080  127.34

In [18]:
df.info()
df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Memory            1303 non-null   object
 9   Gpu               1303 non-null   object
 10  OpSys             1303 non-null   object
 11  Weight            1303 non-null   object
 12  Price_euros       1303 non-null   float64
 13  IPS               1303 non-null   int64
 14  Touchscreen       1303 non-null   int64
 15  X_res             1303 non-null   int64
 16  Y_res             1303 non-null   int64
 17  PPI               1303 non-null   float64
dtypes: float64(3), int64(5), object(10)
memory usage: 183.4+ KB

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,IPS,Touchscreen,X_res,Y_res,PPI
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,1,0,2560,1600,226.98
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,0,0,1440,900,127.68
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,0,0,1920,1080,141.21
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,1,0,2880,1800,220.53
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,1,0,2560,1600,226.98

In [19]:
df.drop(columns=['ScreenResolution'], inplace=True)

In [20]:
df.info()
df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   laptop_ID    1303 non-null   int64
 1   Company      1303 non-null   object
 2   Product      1303 non-null   object
 3   TypeName     1303 non-null   object
 4   Inches       1303 non-null   float64
 5   Cpu          1303 non-null   object
 6   Ram          1303 non-null   object
 7   Memory       1303 non-null   object
 8   Gpu          1303 non-null   object
 9   OpSys        1303 non-null   object
 10  Weight       1303 non-null   object
 11  Price_euros  1303 non-null   float64
 12  IPS          1303 non-null   int64
 13  Touchscreen  1303 non-null   int64
 14  X_res        1303 non-null   int64
 15  Y_res        1303 non-null   int64
 16  PPI          1303 non-null   float64
dtypes: float64(3), int64(5), object(9)
memory usage: 173.2+ KB

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,IPS,Touchscreen,X_res,Y_res,PPI
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,1,0,2560,1600,226.98
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,0,0,1440,900,127.68
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,0,0,1920,1080,141.21
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,1,0,2880,1800,220.53
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,1,0,2560,1600,226.98

# **Preprocessing the " RAM " column :**

In [21]:
df['Ram'] = df['Ram'].str.replace('GB', '').astype('int64')

# **Preprocessing the " Weight " column :**

In [24]:
df['Weight'] = df['Weight'].str.replace('kg', '').astype('float64')

# **Preprocessing the " Memory " column :**

In [34]:
def extract_all_memory_features(mem):
    mem = str(mem)

    # 1. SSD
    has_ssd = 1 if 'SSD' in mem else 0
    ssd_size = 0
    if has_ssd:
        ssd_gb = re.findall(r'(\d+)GB\s*SSD', mem)
        ssd_size += sum([int(x) for x in ssd_gb])
        ssd_tb = re.findall(r'(\d+)TB\s*SSD', mem)
        ssd_size += sum([int(x) * 1024 for x in ssd_tb])

    # 2. HDD
    has_hdd = 1 if 'HDD' in mem else 0
    hdd_size = 0
    if has_hdd:
        hdd_gb = re.findall(r'(\d+)GB\s*HDD', mem)
        hdd_size += sum([int(x) for x in hdd_gb])
        hdd_tb = re.findall(r'(\d+)TB\s*HDD', mem)
        hdd_size += sum([int(x) * 1024 for x in hdd_tb])

    # 3. Flash Memory
    has_flash = 1 if 'Flash' in mem else 0
    flash_size = 0
    if has_flash:
        # استخراج Flash به GB
        flash_gb = re.findall(r'(\d+)GB\s*Flash', mem)
        flash_size += sum([int(x) for x in flash_gb])
        # استخراج Flash به TB (تبدیل به GB)
        flash_tb = re.findall(r'(\d+)TB\s*Flash', mem)
        flash_size += sum([int(x) * 1024 for x in flash_tb])

    # 4. Hybrid (SSHD)
    has_hybrid = 1 if ('Hybrid' in mem or 'SSHD' in mem) else 0
    hybrid_size = 0
    if has_hybrid:
        # استخراج Hybrid به GB
        hybrid_gb = re.findall(r'(\d+)GB\s*(?:Hybrid|SSHD)', mem)
        hybrid_size += sum([int(x) for x in hybrid_gb])
        # استخراج Hybrid به TB (تبدیل به GB)
        hybrid_tb = re.findall(r'(\d+)TB\s*(?:Hybrid|SSHD)', mem)
        hybrid_size += sum([int(x) * 1024 for x in hybrid_tb])

    # 5. محاسبه کل حافظه (همه انواع)
    total_memory = ssd_size + hdd_size + flash_size + hybrid_size

    return has_ssd, ssd_size, has_hdd, hdd_size, has_flash, flash_size, has_hybrid, hybrid_size, total_memory

# اعمال روی دیتافریم
df['Has_SSD'], df['SSD_Size_GB'], df['Has_HDD'], df['HDD_Size_GB'], df['Has_Flash'], df['Flash_Size_GB'], df['Has_Hybrid'], df['Hybrid_Size_GB'], df['Total_Memory_GB'] = zip(*df['Memory'].apply(extract_all_memory_features))

# حذف ستون اصلی Memory
df.drop(columns=['Memory'], inplace=True)

print("✅ پردازش کامل شد!")
print(f"✅ {len(df)} رکورد پردازش شد")

KeyError: 'Memory'

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   laptop_ID        1303 non-null   int64
 1   Company          1303 non-null   object
 2   Product          1303 non-null   object
 3   TypeName         1303 non-null   object
 4   Inches           1303 non-null   float64
 5   Cpu              1303 non-null   object
 6   Ram              1303 non-null   int64
 7   Gpu              1303 non-null   object
 8   OpSys            1303 non-null   object
 9   Weight           1303 non-null   float64
 10  Price_euros      1303 non-null   float64
 11  IPS              1303 non-null   int64
 12  Touchscreen      1303 non-null   int64
 13  X_res            1303 non-null   int64
 14  Y_res            1303 non-null   int64
 15  PPI              1303 non-null   float64
 16  Has_SSD          1303 non-null   int64
 17  SSD_Size_GB      1303 non-null   int64
 18  Has_HDD          1303 non-null   int64
 19  HDD_Size_GB      1303 non-null   int64
 20  Has_Flash        1303 non-null   int64
 21  Flash_Size_GB    1303 non-null   int64
 22  Has_Hybrid       1303 non-null   int64
 23  Hybrid_Size_GB   1303 non-null   int64
 24  Total_Memory_GB  1303 non-null   int64
dtypes: float64(4), int64(15), object(6)
memory usage: 254.6+ KB

In [36]:
df.head(10)

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,...,PPI,Has_SSD,SSD_Size_GB,Has_HDD,HDD_Size_GB,Has_Flash,Flash_Size_GB,Has_Hybrid,Hybrid_Size_GB,Total_Memory_GB
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8,Intel Iris Plus Graphics 640,macOS,1.37,...,226.98,1,128,0,0,0,0,0,0,128
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,...,127.68,0,0,0,0,1,128,0,0,128
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8,Intel HD Graphics 620,No OS,1.86,...,141.21,1,256,0,0,0,0,0,0,256
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16,AMD Radeon Pro 455,macOS,1.83,...,220.53,1,512,0,0,0,0,0,0,512
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8,Intel Iris Plus Graphics 650,macOS,1.37,...,226.98,1,256,0,0,0,0,0,0,256
5,6,Acer,Aspire 3,Notebook,15.6,AMD A9-Series 9420 3GHz,4,AMD Radeon R5,Windows 10,2.10,...,100.45,0,0,1,500,0,0,0,0,500
6,7,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.2GHz,16,Intel Iris Pro Graphics,Mac OS X,2.04,...,220.53,0,0,0,0,1,256,0,0,256
7,8,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8,Intel HD Graphics 6000,macOS,1.34,...,127.68,0,0,0,0,1,256,0,0,256
8,9,Asus,ZenBook UX430UN,Ultrabook,14.0,Intel Core i7 8550U 1.8GHz,16,Nvidia GeForce MX150,Windows 10,1.30,...,157.35,1,512,0,0,0,0,0,0,512
9,10,Acer,Swift 3,Ultrabook,14.0,Intel Core i5 8250U 1.6GHz,8,Intel UHD Graphics 620,Windows 10,1.60,...,157.35,1,256,0,0,0,0,0,0,256

Warning: Total number of columns (25) exceeds max_columns (20) limiting to first (20) columns.

In [37]:
df.describe()

,laptop_ID,Inches,Ram,Weight,Price_euros,IPS,Touchscreen,X_res,Y_res,PPI,Has_SSD,SSD_Size_GB,Has_HDD,HDD_Size_GB,Has_Flash,Flash_Size_GB,Has_Hybrid,Hybrid_Size_GB,Total_Memory_GB
count,1303.000000,1303.000000,1303.000000,1303.000000,1303.000000,1303.000000,1303.000000,1303.000000,1303.000000,1303.000000,1303.000000,1303.000000,1303.000000,1303.000000,1303.000000,1303.000000,1303.00000,1303.000000,1303.000000
mean,660.155794,15.017191,8.382195,2.038734,1123.686992,0.280123,0.147352,1894.784344,1070.830391,146.634589,0.646969,184.027629,0.442057,421.691481,0.057559,4.555641,0.00921,0.389870,610.664620
std,381.172104,1.426304,5.084665,0.665475,699.009043,0.449231,0.354593,494.641028,284.519410,43.121346,0.478096,188.268689,0.496822,527.872349,0.232998,30.274090,0.09556,14.073156,480.507537
min,1.000000,10.100000,2.000000,0.690000,174.000000,0.000000,0.000000,1366.000000,768.000000,90.580000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,331.500000,14.000000,4.000000,1.500000,599.000000,0.000000,0.000000,1600.000000,900.000000,127.340000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,256.000000
50%,659.000000,15.600000,8.000000,2.040000,977.000000,0.000000,0.000000,1920.000000,1080.000000,141.210000,1.000000,256.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,500.000000
75%,990.500000,15.600000,8.000000,2.300000,1487.880000,1.000000,0.000000,1920.000000,1080.000000,157.350000,1.000000,256.000000,1.000000,1024.000000,0.000000,0.000000,0.00000,0.000000,1024.000000
max,1320.000000,18.400000,64.000000,4.700000,6099.000000,1.000000,1.000000,3840.000000,2160.000000,352.470000,1.000000,1024.000000,1.000000,2048.000000,1.000000,512.000000,1.00000,508.000000,2560.000000

In [40]:
df.duplicated().sum()

np.int64(0)

In [41]:
df['Company'].value_counts()

Company
Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Mediacom       7
Razer          7
Microsoft      6
Vero           4
Xiaomi         4
Chuwi          3
Fujitsu        3
Google         3
LG             3
Huawei         2
Name: count, dtype: int64

In [42]:
df['TypeName'].value_counts()

TypeName
Notebook              727
Gaming                205
Ultrabook             196
2 in 1 Convertible    121
Workstation            29
Netbook                25
Name: count, dtype: int64