<a href="https://colab.research.google.com/github/razieabbasi1999/Laptop-Price-Prediction-ML/blob/main/laptop-price-prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
from google.colab import drive

In [3]:
drive.mount('/content/drive')
os.environ['KAGGLE_API_TOKEN'] = "KGAT_f3f655892a6eae5067ca4c0263bd962a"

Mounted at /content/drive

In [4]:
folder_path = '/content/drive/MyDrive/Laptop_Project'

In [5]:
os.chdir(folder_path)

In [6]:
!pip install -q kaggle

In [7]:
!kaggle datasets download -d muhammetvarl/laptop-price

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/muhammetvarl/laptop-price
License(s): other
laptop-price.zip: Skipping, found more recently modified local copy (use --force to force download)

In [8]:
!unzip -o laptop-price.zip

Archive:  laptop-price.zip
  inflating: laptop_price.csv



---

# **Section Data Analysis**

In [9]:
import pandas as pd
df=pd.read_csv("laptop_price.csv", encoding="latin1")

In [10]:
df.head(50)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60
5,6,Acer,Aspire 3,Notebook,15.6,1366x768,AMD A9-Series 9420 3GHz,4GB,500GB HDD,AMD Radeon R5,Windows 10,2.1kg,400.00
6,7,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,2139.97
7,8,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,256GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,1158.70
8,9,Asus,ZenBook UX430UN,Ultrabook,14.0,Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16GB,512GB SSD,Nvidia GeForce MX150,Windows 10,1.3kg,1495.00
9,10,Acer,Swift 3,Ultrabook,14.0,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Intel UHD Graphics 620,Windows 10,1.6kg,770.00
10,11,HP,250 G6,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,No OS,1.86kg,393.90
11,12,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,500GB HDD,Intel HD Graphics 520,No OS,1.86kg,344.99
12,13,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.8GHz,16GB,256GB SSD,AMD Radeon Pro 555,macOS,1.83kg,2439.97
13,14,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,256GB SSD,AMD Radeon R5 M430,Windows 10,2.2kg,498.90
14,15,Apple,"MacBook 12""",Ultrabook,12.0,IPS Panel Retina Display 2304x1440,Intel Core M m3 1.2GHz,8GB,256GB SSD,Intel HD Graphics 615,macOS,0.92kg,1262.40
15,16,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,256GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1518.55
16,17,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,256GB SSD,AMD Radeon R5 M430,Windows 10,2.2kg,745.00
17,18,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.9GHz,16GB,512GB SSD,AMD Radeon Pro 560,macOS,1.83kg,2858.00
18,19,Lenovo,IdeaPad 320-15IKB,Notebook,15.6,Full HD 1920x1080,Intel Core i3 7100U 2.4GHz,8GB,1TB HDD,Nvidia GeForce 940MX,No OS,2.2kg,499.00
19,20,Dell,XPS 13,Ultrabook,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,128GB SSD,Intel UHD Graphics 620,Windows 10,1.22kg,979.00
20,21,Asus,Vivobook E200HA,Netbook,11.6,1366x768,Intel Atom x5-Z8350 1.44GHz,2GB,32GB Flash Storage,Intel HD Graphics 400,Windows 10,0.98kg,191.90
21,22,Lenovo,Legion Y520-15IKBN,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,8GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1050,Windows 10,2.5kg,999.00
22,23,HP,255 G6,Notebook,15.6,1366x768,AMD E-Series E2-9000e 1.5GHz,4GB,500GB HDD,AMD Radeon R2,No OS,1.86kg,258.00
23,24,Dell,Inspiron 5379,2 in 1 Convertible,13.3,Full HD / Touchscreen 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Intel UHD Graphics 620,Windows 10,1.62kg,819.00
24,25,HP,15-BS101nv (i7-8550U/8GB/256GB/FHD/W10),Ultrabook,15.6,Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.91kg,659.00
25,26,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i3 6006U 2GHz,4GB,1TB HDD,Intel HD Graphics 520,Windows 10,2.3kg,418.64
26,27,Apple,MacBook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.6GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,Mac OS X,1.35kg,1099.00
27,28,Dell,Inspiron 5570,Notebook,15.6,Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,AMD Radeon 530,Windows 10,2.2kg,800.00
28,29,Dell,Latitude 5590,Ultrabook,15.6,Full HD 1920x1080,Intel Core i7 8650U 1.9GHz,8GB,256GB SSD + 256GB SSD,Intel UHD Graphics 620,Windows 10,1.88kg,1298.00
29,30,HP,ProBook 470,Notebook,17.3,Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,1TB HDD,Nvidia GeForce 930MX,Windows 10,2.5kg,896.00
30,31,Chuwi,"LapBook 15.6""",Notebook,15.6,Full HD 1920x1080,Intel Atom x5-Z8300 1.44GHz,4GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.89kg,244.99
31,32,Asus,E402WA-GA010T (E2-6110/2GB/32GB/W10),Notebook,14.0,1366x768,AMD E-Series E2-6110 1.5GHz,2GB,32GB Flash Storage,AMD Radeon R2,Windows 10,1.65kg,199.00
32,33,HP,17-ak001nv (A6-9220/4GB/500GB/Radeon,Notebook,17.3,Full HD 1920x1080,AMD A6-Series 9220 2.5GHz,4GB,500GB HDD,AMD Radeon 530,Windows 10,2.71kg,439.00
33,34,Dell,XPS 13,Ultrabook,13.3,Touchscreen / Quad HD+ 3200x1800,Intel Core i7 8550U 1.8GHz,16GB,512GB SSD,Intel UHD Graphics 620,Windows 10,1.2kg,1869.00
34,35,Apple,MacBook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.6GHz,8GB,256GB Flash Storage,Intel HD Graphics 6000,Mac OS X,1.35kg,998.00
35,36,Lenovo,IdeaPad 120S-14IAP,Notebook,14.0,1366x768,Intel Celeron Dual Core N3350 1.1GHz,4GB,64GB Flash Storage,Intel HD Graphics 500,Windows 10,1.44kg,249.00
36,37,Acer,Aspire 3,Notebook,15.6,1366x768,Intel Core i3 7130U 2.7GHz,4GB,1TB HDD,Intel HD Graphics 620,Linux,2.1kg,367.00
37,38,Dell,Inspiron 5770,Notebook,17.3,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,128GB SSD + 1TB HDD,AMD Radeon 530,Windows 10,2.8kg,979.00
38,39,HP,250 G6,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,4GB,1TB HDD,Intel HD Graphics 620,Windows 10,1.86kg,488.69
39,40,HP,ProBook 450,Notebook,15.6,Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Nvidia GeForce 930MX,Windows 10,2.1kg,879.00
40,41,Asus,X540UA-DM186 (i3-6006U/4GB/1TB/FHD/Linux),Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,1TB HDD,Intel HD Graphics 620,Linux,2kg,389.00
41,42,Dell,Inspiron 7577,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1060,Windows 10,2.65kg,1499.00
42,43,Asus,X542UQ-GO005 (i5-7200U/8GB/1TB/GeForce,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,8GB,1TB HDD,Nvidia GeForce 940MX,Linux,2.3kg,522.99
43,44,Acer,Aspire A515-51G,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,4GB,256GB SSD,Intel UHD Graphics 620,Windows 10,2.2kg,682.00
44,45,Dell,Inspiron 7773,2 in 1 Convertible,17.3,Full HD / Touchscreen 1920x1080,Intel Core i5 8250U 1.6GHz,12GB,1TB HDD,Nvidia GeForce 150MX,Windows 10,2.77kg,999.00
45,46,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.0GHz,8GB,256GB SSD,Intel Iris Graphics 540,macOS,1.37kg,1419.00
46,47,Lenovo,IdeaPad 320-15ISK,Notebook,15.6,1366x768,Intel Core i3 6006U 2GHz,4GB,128GB SSD,Intel HD Graphics 520,No OS,2.2kg,369.00
47,48,Asus,Rog Strix,Gaming,17.3,Full HD 1920x1080,AMD Ryzen 1700 3GHz,8GB,256GB SSD + 1TB HDD,AMD Radeon RX 580,Windows 10,3.2kg,1299.00
48,49,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,256GB SSD,AMD Radeon R5 M430,Windows 10,2.3kg,639.00
49,50,Asus,X751NV-TY001T (N4200/4GB/1TB/GeForce,Notebook,17.3,1366x768,Intel Pentium Quad Core N4200 1.1GHz,4GB,1TB HDD,Nvidia GeForce 920MX,Windows 10,2.8kg,466.00

In [12]:
df.shape

(1303, 13)

In [13]:
df.columns

Index(['laptop_ID', 'Company', 'Product', 'TypeName', 'Inches',
       'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight',
       'Price_euros'],
      dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Memory            1303 non-null   object
 9   Gpu               1303 non-null   object
 10  OpSys             1303 non-null   object
 11  Weight            1303 non-null   object
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 132.5+ KB

# **Preprocessing the " ScreenResolution " column :**

In [15]:
import numpy as np
import re

In [16]:
# ۱: IPS  ,  Touchscreen
df['IPS'] = df['ScreenResolution'].apply(lambda x: 1 if 'IPS' in x else 0)
df['Touchscreen'] = df['ScreenResolution'].apply(
lambda x: 1 if 'Touchscreen' in x else 0)

In [17]:
# 2.1: Height and width extraction function
def extract_resolution(res):
  match = re.search(r'(\d+)x(\d+)', res)
  if match:
    return int(match.group(1)), int(match.group(2))
  return None, None


# 2.2: Creating columns X_res and Y_res
res_tuples = df['ScreenResolution'].apply(extract_resolution)
df['X_res'], df['Y_res'] = zip(*res_tuples)

In [18]:
# 4: PPI calculation
df['PPI'] = (
(df['X_res'] ** 2 + df['Y_res'] ** 2) ** 0.5 / df['Inches']).round(2)

In [19]:
# ۵. نمایش هر ۵ ستون ساخته‌شده
df[['IPS', 'Touchscreen', 'X_res', 'Y_res', 'PPI']].head(30)

    IPS  Touchscreen  X_res  Y_res     PPI
0     1            0   2560   1600  226.98
1     0            0   1440    900  127.68
2     0            0   1920   1080  141.21
3     1            0   2880   1800  220.53
4     1            0   2560   1600  226.98
5     0            0   1366    768  100.45
6     1            0   2880   1800  220.53
7     0            0   1440    900  127.68
8     0            0   1920   1080  157.35
9     1            0   1920   1080  157.35
10    0            0   1366    768  100.45
11    0            0   1920   1080  141.21
12    1            0   2880   1800  220.53
13    0            0   1920   1080  141.21
14    1            0   2304   1440  226.42
15    1            0   2560   1600  226.98
16    0            0   1920   1080  141.21
17    1            0   2880   1800  220.53
18    0            0   1920   1080  141.21
19    1            1   1920   1080  165.63
20    0            0   1366    768  135.09
21    1            0   1920   1080  141.21
22    0            0   1366    768  100.45
23    0            1   1920   1080  165.63
24    0            0   1920   1080  141.21
25    0            0   1366    768  100.45
26    0            0   1440    900  127.68
27    0            0   1920   1080  141.21
28    0            0   1920   1080  141.21
29    0            0   1920   1080  127.34

In [32]:
df.info()
df.head(50)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   laptop_ID      1303 non-null   int64
 1   Company        1303 non-null   object
 2   Product        1303 non-null   object
 3   TypeName       1303 non-null   object
 4   Inches         1303 non-null   float64
 5   Cpu            1303 non-null   object
 6   Ram            1303 non-null   int64
 7   Memory         1303 non-null   object
 8   Gpu            1303 non-null   object
 9   OpSys          1303 non-null   object
 10  Weight         1303 non-null   float64
 11  Price_euros    1303 non-null   float64
 12  IPS            1303 non-null   int64
 13  Touchscreen    1303 non-null   int64
 14  X_res          1303 non-null   int64
 15  Y_res          1303 non-null   int64
 16  PPI            1303 non-null   float64
 17  Cpu_Speed_GHz  1303 non-null   float64
 18  Cpu_Brand      1303 non-null   object
dtypes: float64(5), int64(6), object(8)
memory usage: 193.5+ KB

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,IPS,Touchscreen,X_res,Y_res,PPI,Cpu_Speed_GHz,Cpu_Brand
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,1,0,2560,1600,226.98,2.30,Intel Core i5
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,898.94,0,0,1440,900,127.68,1.80,Intel Core i5
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,575.00,0,0,1920,1080,141.21,2.50,Intel Core i5
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,2537.45,1,0,2880,1800,220.53,2.70,Intel Core i7
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,1,0,2560,1600,226.98,3.10,Intel Core i5
5,6,Acer,Aspire 3,Notebook,15.6,AMD A9-Series 9420 3GHz,4,500GB HDD,AMD Radeon R5,Windows 10,2.10,400.00,0,0,1366,768,100.45,3.00,AMD Budget
6,7,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.2GHz,16,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04,2139.97,1,0,2880,1800,220.53,2.20,Intel Core i7
7,8,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8,256GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,1158.70,0,0,1440,900,127.68,1.80,Intel Core i5
8,9,Asus,ZenBook UX430UN,Ultrabook,14.0,Intel Core i7 8550U 1.8GHz,16,512GB SSD,Nvidia GeForce MX150,Windows 10,1.30,1495.00,0,0,1920,1080,157.35,1.80,Intel Core i7
9,10,Acer,Swift 3,Ultrabook,14.0,Intel Core i5 8250U 1.6GHz,8,256GB SSD,Intel UHD Graphics 620,Windows 10,1.60,770.00,1,0,1920,1080,157.35,1.60,Intel Core i5
10,11,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,4,500GB HDD,Intel HD Graphics 620,No OS,1.86,393.90,0,0,1366,768,100.45,2.50,Intel Core i5
11,12,HP,250 G6,Notebook,15.6,Intel Core i3 6006U 2GHz,4,500GB HDD,Intel HD Graphics 520,No OS,1.86,344.99,0,0,1920,1080,141.21,2.00,Intel Core i3
12,13,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.8GHz,16,256GB SSD,AMD Radeon Pro 555,macOS,1.83,2439.97,1,0,2880,1800,220.53,2.80,Intel Core i7
13,14,Dell,Inspiron 3567,Notebook,15.6,Intel Core i3 6006U 2GHz,4,256GB SSD,AMD Radeon R5 M430,Windows 10,2.20,498.90,0,0,1920,1080,141.21,2.00,Intel Core i3
14,15,Apple,"MacBook 12""",Ultrabook,12.0,Intel Core M m3 1.2GHz,8,256GB SSD,Intel HD Graphics 615,macOS,0.92,1262.40,1,0,2304,1440,226.42,1.20,Intel Other
15,16,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8,256GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,1518.55,1,0,2560,1600,226.98,2.30,Intel Core i5
16,17,Dell,Inspiron 3567,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8,256GB SSD,AMD Radeon R5 M430,Windows 10,2.20,745.00,0,0,1920,1080,141.21,2.70,Intel Core i7
17,18,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.9GHz,16,512GB SSD,AMD Radeon Pro 560,macOS,1.83,2858.00,1,0,2880,1800,220.53,2.90,Intel Core i7
18,19,Lenovo,IdeaPad 320-15IKB,Notebook,15.6,Intel Core i3 7100U 2.4GHz,8,1TB HDD,Nvidia GeForce 940MX,No OS,2.20,499.00,0,0,1920,1080,141.21,2.40,Intel Core i3
19,20,Dell,XPS 13,Ultrabook,13.3,Intel Core i5 8250U 1.6GHz,8,128GB SSD,Intel UHD Graphics 620,Windows 10,1.22,979.00,1,1,1920,1080,165.63,1.60,Intel Core i5
20,21,Asus,Vivobook E200HA,Netbook,11.6,Intel Atom x5-Z8350 1.44GHz,2,32GB Flash Storage,Intel HD Graphics 400,Windows 10,0.98,191.90,0,0,1366,768,135.09,1.44,Intel Budget
21,22,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Intel Core i5 7300HQ 2.5GHz,8,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1050,Windows 10,2.50,999.00,1,0,1920,1080,141.21,2.50,Intel Core i5
22,23,HP,255 G6,Notebook,15.6,AMD E-Series E2-9000e 1.5GHz,4,500GB HDD,AMD Radeon R2,No OS,1.86,258.00,0,0,1366,768,100.45,1.50,AMD Budget
23,24,Dell,Inspiron 5379,2 in 1 Convertible,13.3,Intel Core i5 8250U 1.6GHz,8,256GB SSD,Intel UHD Graphics 620,Windows 10,1.62,819.00,0,1,1920,1080,165.63,1.60,Intel Core i5
24,25,HP,15-BS101nv (i7-8550U/8GB/256GB/FHD/W10),Ultrabook,15.6,Intel Core i7 8550U 1.8GHz,8,256GB SSD,Intel HD Graphics 620,Windows 10,1.91,659.00,0,0,1920,1080,141.21,1.80,Intel Core i7
25,26,Dell,Inspiron 3567,Notebook,15.6,Intel Core i3 6006U 2GHz,4,1TB HDD,Intel HD Graphics 520,Windows 10,2.30,418.64,0,0,1366,768,100.45,2.00,Intel Core i3
26,27,Apple,MacBook Air,Ultrabook,13.3,Intel Core i5 1.6GHz,8,128GB Flash Storage,Intel HD Graphics 6000,Mac OS X,1.35,1099.00,0,0,1440,900,127.68,1.60,Intel Core i5
27,28,Dell,Inspiron 5570,Notebook,15.6,Intel Core i5 8250U 1.6GHz,8,256GB SSD,AMD Radeon 530,Windows 10,2.20,800.00,0,0,1920,1080,141.21,1.60,Intel Core i5
28,29,Dell,Latitude 5590,Ultrabook,15.6,Intel Core i7 8650U 1.9GHz,8,256GB SSD + 256GB SSD,Intel UHD Graphics 620,Windows 10,1.88,1298.00,0,0,1920,1080,141.21,1.90,Intel Core i7
29,30,HP,ProBook 470,Notebook,17.3,Intel Core i5 8250U 1.6GHz,8,1TB HDD,Nvidia GeForce 930MX,Windows 10,2.50,896.00,0,0,1920,1080,127.34,1.60,Intel Core i5
30,31,Chuwi,"LapBook 15.6""",Notebook,15.6,Intel Atom x5-Z8300 1.44GHz,4,64GB Flash Storage,Intel HD Graphics,Windows 10,1.89,244.99,0,0,1920,1080,141.21,1.44,Intel Budget
31,32,Asus,E402WA-GA010T (E2-6110/2GB/32GB/W10),Notebook,14.0,AMD E-Series E2-6110 1.5GHz,2,32GB Flash Storage,AMD Radeon R2,Windows 10,1.65,199.00,0,0,1366,768,111.94,1.50,AMD Budget
32,33,HP,17-ak001nv (A6-9220/4GB/500GB/Radeon,Notebook,17.3,AMD A6-Series 9220 2.5GHz,4,500GB HDD,AMD Radeon 530,Windows 10,2.71,439.00,0,0,1920,1080,127.34,2.50,AMD Budget
33,34,Dell,XPS 13,Ultrabook,13.3,Intel Core i7 8550U 1.8GHz,16,512GB SSD,Intel UHD Graphics 620,Windows 10,1.20,1869.00,0,1,3200,1800,276.05,1.80,Intel Core i7
34,35,Apple,MacBook Air,Ultrabook,13.3,Intel Core i5 1.6GHz,8,256GB Flash Storage,Intel HD Graphics 6000,Mac OS X,1.35,998.00,0,0,1440,900,127.68,1.60,Intel Core i5
35,36,Lenovo,IdeaPad 120S-14IAP,Notebook,14.0,Intel Celeron Dual Core N3350 1.1GHz,4,64GB Flash Storage,Intel HD Graphics 500,Windows 10,1.44,249.00,0,0,1366,768,111.94,1.10,Intel Budget
36,37,Acer,Aspire 3,Notebook,15.6,Intel Core i3 7130U 2.7GHz,4,1TB HDD,Intel HD Graphics 620,Linux,2.10,367.00,0,0,1366,768,100.45,2.70,Intel Core i3
37,38,Dell,Inspiron 5770,Notebook,17.3,Intel Core i5 8250U 1.6GHz,8,128GB SSD + 1TB HDD,AMD Radeon 530,Windows 10,2.80,979.00,1,0,1920,1080,127.34,1.60,Intel Core i5
38,39,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,4,1TB HDD,Intel HD Graphics 620,Windows 10,1.86,488.69,0,0,1366,768,100.45,2.50,Intel Core i5
39,40,HP,ProBook 450,Notebook,15.6,Intel Core i5 8250U 1.6GHz,8,256GB SSD,Nvidia GeForce 930MX,Windows 10,2.10,879.00,0,0,1920,1080,141.21,1.60,Intel Core i5
40,41,Asus,X540UA-DM186 (i3-6006U/4GB/1TB/FHD/Linux),Notebook,15.6,Intel Core i3 6006U 2GHz,4,1TB HDD,Intel HD Graphics 620,Linux,2.00,389.00,0,0,1920,1080,141.21,2.00,Intel Core i3
41,42,Dell,Inspiron 7577,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,16,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1060,Windows 10,2.65,1499.00,1,0,1920,1080,141.21,2.80,Intel Core i7
42,43,Asus,X542UQ-GO005 (i5-7200U/8GB/1TB/GeForce,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8,1TB HDD,Nvidia GeForce 940MX,Linux,2.30,522.99,0,0,1366,768,100.45,2.50,Intel Core i5
43,44,Acer,Aspire A515-51G,Notebook,15.6,Intel Core i5 8250U 1.6GHz,4,256GB SSD,Intel UHD Graphics 620,Windows 10,2.20,682.00,1,0,1920,1080,141.21,1.60,Intel Core i5
44,45,Dell,Inspiron 7773,2 in 1 Convertible,17.3,Intel Core i5 8250U 1.6GHz,12,1TB HDD,Nvidia GeForce 150MX,Windows 10,2.77,999.00,0,1,1920,1080,127.34,1.60,Intel Core i5
45,46,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.0GHz,8,256GB SSD,Intel Iris Graphics 540,macOS,1.37,1419.00,1,0,2560,1600,226.98,2.00,Intel Core i5
46,47,Lenovo,IdeaPad 320-15ISK,Notebook,15.6,Intel Core i3 6006U 2GHz,4,128GB SSD,Intel HD Graphics 520,No OS,2.20,369.00,0,0,1366,768,100.45,2.00,Intel Core i3
47,48,Asus,Rog Strix,Gaming,17.3,AMD Ryzen 1700 3GHz,8,256GB SSD + 1TB HDD,AMD Radeon RX 580,Windows 10,3.20,1299.00,0,0,1920,1080,127.34,3.00,AMD Ryzen
48,49,Dell,Inspiron 3567,Notebook,15.6,Intel Core i5 7200U 2.5GHz,4,256GB SSD,AMD Radeon R5 M430,Windows 10,2.30,639.00,0,0,1920,1080,141.21,2.50,Intel Core i5
49,50,Asus,X751NV-TY001T (N4200/4GB/1TB/GeForce,Notebook,17.3,Intel Pentium Quad Core N4200 1.1GHz,4,1TB HDD,Nvidia GeForce 920MX,Windows 10,2.80,466.00,0,0,1366,768,90.58,1.10,Intel Budget

In [21]:
df.drop(columns=['ScreenResolution'], inplace=True)

In [22]:
df.info()
df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   laptop_ID    1303 non-null   int64
 1   Company      1303 non-null   object
 2   Product      1303 non-null   object
 3   TypeName     1303 non-null   object
 4   Inches       1303 non-null   float64
 5   Cpu          1303 non-null   object
 6   Ram          1303 non-null   object
 7   Memory       1303 non-null   object
 8   Gpu          1303 non-null   object
 9   OpSys        1303 non-null   object
 10  Weight       1303 non-null   object
 11  Price_euros  1303 non-null   float64
 12  IPS          1303 non-null   int64
 13  Touchscreen  1303 non-null   int64
 14  X_res        1303 non-null   int64
 15  Y_res        1303 non-null   int64
 16  PPI          1303 non-null   float64
dtypes: float64(3), int64(5), object(9)
memory usage: 173.2+ KB

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,IPS,Touchscreen,X_res,Y_res,PPI
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,1,0,2560,1600,226.98
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,0,0,1440,900,127.68
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,0,0,1920,1080,141.21
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,1,0,2880,1800,220.53
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,1,0,2560,1600,226.98

# **Preprocessing the " RAM " column :**

In [23]:
df['Ram'] = df['Ram'].str.replace('GB', '').astype('int64')

# **Preprocessing the " Weight " column :**

In [25]:
df['Weight'] = df['Weight'].str.replace('kg', '').astype('float64')

# **Preprocessing the " CPU " column :**

In [36]:
print("تعداد تنوع متنی در ستون Cpu:", df['Cpu'].nunique())

تعداد تنوع متنی در ستون Cpu: 118

In [38]:
# ۱. Extracting frequency (speed) as a numerical variable
def extract_cpu_speed(cpu_str):
  match = re.search(r'(\d+(?:\.\d+)?)GHz', cpu_str)
  if match:
    return float(match.group(1))
  return None

df['Cpu_Speed_GHz'] = df['Cpu'].apply(extract_cpu_speed)

# ۲. Processor categories
def fetch_cpu_brand(cpu_str):
  if 'Intel Core i7' in cpu_str:
    return 'Intel Core i7'
  elif 'Intel Core i5' in cpu_str:
    return 'Intel Core i5'
  elif 'Intel Core i3' in cpu_str:
    return 'Intel Core i3'
  elif 'Celeron' in cpu_str or 'Pentium' in cpu_str:
    return 'Intel Budget'
  elif 'Intel' in cpu_str:
    return 'Intel Other'
  elif 'AMD' in cpu_str:
    return 'AMD'
  else:
    return 'Intel Other'

df['Cpu_Brand'] = df['Cpu'].apply(fetch_cpu_brand)
print(df['Cpu_Brand'].value_counts())

Cpu_Brand
Intel Core i7    527
Intel Core i5    423
Intel Core i3    136
Intel Budget     118
AMD               62
Intel Other       37
Name: count, dtype: int64

# **Preprocessing the " Nemory " column :**

In [41]:
def extract_memory_features(memory_str):
  ssd, hdd, flash, hybrid = 0, 0, 0, 0

  # ۱. Convert TB to GB
  memory_str = memory_str.replace('1.0TB', '1024GB').replace('1TB', '1024GB')
  memory_str = memory_str.replace('2TB', '2048GB')

  # ۲. Separation, for example, 128GB SSD + 1TB HDD
  parts = memory_str.split('+')

  for part in parts:
    part = part.strip()
    match = re.search(r'(\d+)GB', part)
    if match:
      size = int(match.group(1))
      if 'SSD' in part:
        ssd += size
      elif 'HDD' in part:
        hdd += size
      elif 'Flash' in part:
        flash += size
      elif 'Hybrid' in part:
        hybrid += size

  return ssd, hdd, flash, hybrid


# Create 4 new numeric columns
(
    df['SSD_GB'],
    df['HDD_GB'],
    df['Flash_Storage_GB'],
    df['Hybrid_GB'],
) = zip(*df['Memory'].apply(extract_memory_features))

df[['Memory', 'SSD_GB', 'HDD_GB', 'Flash_Storage_GB', 'Hybrid_GB']].head(10)

                Memory  SSD_GB  HDD_GB  Flash_Storage_GB  Hybrid_GB
0            128GB SSD     128       0                 0          0
1  128GB Flash Storage       0       0               128          0
2            256GB SSD     256       0                 0          0
3            512GB SSD     512       0                 0          0
4            256GB SSD     256       0                 0          0
5            500GB HDD       0     500                 0          0
6  256GB Flash Storage       0       0               256          0
7  256GB Flash Storage       0       0               256          0
8            512GB SSD     512       0                 0          0
9            256GB SSD     256       0                 0          0

In [42]:
df.info()
df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   Cpu               1303 non-null   object
 6   Ram               1303 non-null   int64
 7   Memory            1303 non-null   object
 8   Gpu               1303 non-null   object
 9   OpSys             1303 non-null   object
 10  Weight            1303 non-null   float64
 11  Price_euros       1303 non-null   float64
 12  IPS               1303 non-null   int64
 13  Touchscreen       1303 non-null   int64
 14  X_res             1303 non-null   int64
 15  Y_res             1303 non-null   int64
 16  PPI               1303 non-null   float64
 17  Cpu_Speed_GHz     1303 non-null   float64
 18  Cpu_Brand         1303 non-null   object
 19  SSD_GB            1303 non-null   int64
 20  HDD_GB            1303 non-null   int64
 21  Flash_Storage_GB  1303 non-null   int64
 22  Hybrid_GB         1303 non-null   int64
dtypes: float64(5), int64(10), object(8)
memory usage: 234.3+ KB

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Memory,Gpu,OpSys,...,Touchscreen,X_res,Y_res,PPI,Cpu_Speed_GHz,Cpu_Brand,SSD_GB,HDD_GB,Flash_Storage_GB,Hybrid_GB
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,...,0,2560,1600,226.98,2.3,Intel Core i5,128,0,0,0
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,...,0,1440,900,127.68,1.8,Intel Core i5,0,0,128,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,...,0,1920,1080,141.21,2.5,Intel Core i5,256,0,0,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,...,0,2880,1800,220.53,2.7,Intel Core i7,512,0,0,0
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,...,0,2560,1600,226.98,3.1,Intel Core i5,256,0,0,0

In [45]:
df.drop(columns=['Cpu', 'Memory'], inplace=True)

KeyError: "['Cpu', 'Memory'] not found in axis"

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   Ram               1303 non-null   int64
 6   Gpu               1303 non-null   object
 7   OpSys             1303 non-null   object
 8   Weight            1303 non-null   float64
 9   Price_euros       1303 non-null   float64
 10  IPS               1303 non-null   int64
 11  Touchscreen       1303 non-null   int64
 12  X_res             1303 non-null   int64
 13  Y_res             1303 non-null   int64
 14  PPI               1303 non-null   float64
 15  Cpu_Speed_GHz     1303 non-null   float64
 16  Cpu_Brand         1303 non-null   object
 17  SSD_GB            1303 non-null   int64
 18  HDD_GB            1303 non-null   int64
 19  Flash_Storage_GB  1303 non-null   int64
 20  Hybrid_GB         1303 non-null   int64
dtypes: float64(5), int64(10), object(6)
memory usage: 213.9+ KB

In [53]:
print(" Number of Data Gpu:", df['Gpu'].nunique())

 Number of Data Gpu: 110

In [54]:
def fetch_gpu_brand(gpu_str):
  return gpu_str.split()[0]


df['Gpu_Brand'] = df['Gpu'].apply(fetch_gpu_brand)

print("--- Number of data GPU ---")
print(df['Gpu_Brand'].value_counts())

df[['Gpu', 'Gpu_Brand']].head(10)

--- Number of data GPU ---
Gpu_Brand
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64

                            Gpu Gpu_Brand
0  Intel Iris Plus Graphics 640     Intel
1        Intel HD Graphics 6000     Intel
2         Intel HD Graphics 620     Intel
3            AMD Radeon Pro 455       AMD
4  Intel Iris Plus Graphics 650     Intel
5                 AMD Radeon R5       AMD
6       Intel Iris Pro Graphics     Intel
7        Intel HD Graphics 6000     Intel
8          Nvidia GeForce MX150    Nvidia
9        Intel UHD Graphics 620     Intel

In [ ]:
df = df[df['Gpu_Brand'] != 'ARM']
df.drop(columns=['Gpu'], inplace=True)

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1302 entries, 0 to 1302
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1302 non-null   int64
 1   Company           1302 non-null   object
 2   Product           1302 non-null   object
 3   TypeName          1302 non-null   object
 4   Inches            1302 non-null   float64
 5   Ram               1302 non-null   int64
 6   OpSys             1302 non-null   object
 7   Weight            1302 non-null   float64
 8   Price_euros       1302 non-null   float64
 9   IPS               1302 non-null   int64
 10  Touchscreen       1302 non-null   int64
 11  X_res             1302 non-null   int64
 12  Y_res             1302 non-null   int64
 13  PPI               1302 non-null   float64
 14  Cpu_Speed_GHz     1302 non-null   float64
 15  Cpu_Brand         1302 non-null   object
 16  SSD_GB            1302 non-null   int64
 17  HDD_GB            1302 non-null   int64
 18  Flash_Storage_GB  1302 non-null   int64
 19  Hybrid_GB         1302 non-null   int64
 20  Gpu_Brand         1302 non-null   object
dtypes: float64(5), int64(10), object(6)
memory usage: 223.8+ KB

In [59]:
print(" Number of Data OpSys:", df['OpSys'].nunique())

 Number of Data OpSys: 9